#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

foamClearPolyMesh 
rm -rf 0/alpha1 0/alpha1.gz probes wallPressure pRefProbe

# ----------------------------------------------------------------- end-of-file
